name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # <--- essentieel

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # mag ook v3 zijn, maar v4 is nieuwer

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
